import * as THREE from "three";
import { smoothstep } from "./utils.js";
import { createPaletteCycler } from "./palette.js";

// ---- A fake fluid/smoke field: no simulation state, just a fragment
// shader advecting sample coordinates through a curl noise field (the
// gradient of an fbm "potential," rotated 90 degrees, which makes it
// divergence-free — genuine vortices and eddies rather than folded noise).
// Rendered on one big plane sized to cover the camera's frustum, so it
// reads as a full-screen effect while still living inside the normal
// scene/camera/composer pipeline. ----

const PLANE_WIDTH = 120;
const PLANE_HEIGHT = 70;
const PLANE_Z = -15; // distance from the camera determines how large this needs to be

const NOISE_SCALE = 0.06; // world units -> noise space; smaller = larger swirls
const FLOW_SPEED = 0.01; // how fast the flow evolves over time
const CURL_EPSILON = 0.1; // detail scale of the curl sampling — small = finer/grainier, large = smoother/blurrier
const CURL_STRENGTH = 10.0; // how far each advection step displaces the sample point
const TIME_LOOP_RADIUS = 10.0; // how far the time-driven wander displaces the sample point

const FADE_IN_DURATION = 1.4;

// JS stringifies whole numbers without a decimal point (e.g. 4 -> "4"),
// which GLSL ES rejects when mixed with float/vec math — force one.
function glslFloat(n) {
  return Number.isInteger(n) ? n.toFixed(1) : String(n);
}

const VERTEX_SHADER = `
varying vec2 vPos;
void main() {
  vPos = position.xy;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
`;

const FRAGMENT_SHADER = `
uniform float uTime;
uniform vec3 uColorA;
uniform vec3 uColorB;
uniform vec3 uColorC;
uniform vec3 uColorD;
uniform float uGlitch;
uniform float uFadeIn;
varying vec2 vPos;

float random(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
}

float noise(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  float a = random(i);
  float b = random(i + vec2(1.0, 0.0));
  float c = random(i + vec2(0.0, 1.0));
  float d = random(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float value = 0.0;
  float amp = 0.5;
  for (int i = 0; i < 5; i++) {
    value += amp * noise(p);
    p *= 2.0;
    amp *= 0.5;
  }
  return value;
}

// Curl of an fbm "potential" field: the gradient rotated 90 degrees.
// Unlike raw fbm, this is divergence-free — it has no sources or sinks,
// so following it traces closed loops and vortices instead of the field
// just bunching up or draining toward high/low points. That's what makes
// it read as genuine swirling flow rather than folded noise.
vec2 curl(vec2 p) {
  float eps = ${glslFloat(CURL_EPSILON)};
  float dx = fbm(p + vec2(eps, 0.0)) - fbm(p - vec2(eps, 0.0));
  float dy = fbm(p + vec2(0.0, eps)) - fbm(p - vec2(0.0, eps));
  // no "/ (2.0 * eps)" here on purpose — dividing by the sample step
  // would make the output magnitude blow up as eps shrinks, coupling
  // CURL_EPSILON to CURL_STRENGTH/TIME_LOOP_RADIUS in a way that makes
  // them fight each other. Leaving it undivided keeps eps purely a
  // "detail scale" knob (how localized the sampling is) while the other
  // two independently control displacement distance.
  return vec2(dy, -dx);
}

void main() {
  vec2 p = vPos * ${glslFloat(NOISE_SCALE)};
  float t = uTime * ${glslFloat(FLOW_SPEED)};

  // drive the time offset from the curl field itself instead of a plain
  // cos/sin circle — a geometric circle reads as the whole pattern
  // visibly orbiting, while walking a slowly-drifting point through the
  // (chaotic, bounded) curl field produces organic, non-repeating wander
  vec2 timeLoop1 = curl(vec2(4.1, 2.3) + t * 0.4) * ${glslFloat(TIME_LOOP_RADIUS)};
  vec2 timeLoop2 = curl(vec2(9.7, 5.5) - t * 0.35) * ${glslFloat(TIME_LOOP_RADIUS)};

  // advect the sample point through the curl field twice, each step
  // riding the flow generated by the previous one — this is what
  // produces nested eddies and vortices instead of a single warp
  vec2 flow1 = curl(p + timeLoop1);
  vec2 p1 = p + flow1 * ${glslFloat(CURL_STRENGTH)};

  vec2 flow2 = curl(p1 * 0.6 + vec2(5.2, 1.3) + timeLoop2);
  vec2 p2 = p1 + flow2 * ${glslFloat(CURL_STRENGTH)};

  float f = fbm(p2);

  vec3 color = mix(uColorA, uColorB, clamp(f, 0.0, 1.0));
  color = mix(color, uColorC, clamp(length(flow1) * 1.2, 0.0, 1.0));
  color = mix(color, uColorD, clamp(length(flow2) * 1.2, 0.0, 1.0));

  // no base floor here — real dark troughs (not just dimmer color) are
  // what let the bloom pass pick out the bright swirls instead of
  // blowing out the entire screen, since bloom has zero threshold
  float glow = clamp(f * f * f * 1.6, 0.0, 1.0);
  color *= glow;

  if (uGlitch > 0.5) {
    float strobe = random(vPos * 0.01 + uTime);
    color *= strobe < 0.5 ? 0.1 : 2.2;
  }

  color *= uFadeIn;

  gl_FragColor = vec4(color, 1.0);
}
`;

export function createFluidField() {
  const geometry = new THREE.PlaneGeometry(PLANE_WIDTH, PLANE_HEIGHT);
  const paletteCycler = createPaletteCycler();
  const palette = paletteCycler.palette;

  const uniforms = {
    uTime: { value: 0 },
    uColorA: { value: new THREE.Color(palette[0]) },
    uColorB: { value: new THREE.Color(palette[1]) },
    uColorC: { value: new THREE.Color(palette[2] ?? palette[0]) },
    uColorD: { value: new THREE.Color(palette[3] ?? palette[1]) },
    uGlitch: { value: 0 },
    uFadeIn: { value: 0 },
  };

  const material = new THREE.ShaderMaterial({
    vertexShader: VERTEX_SHADER,
    fragmentShader: FRAGMENT_SHADER,
    uniforms,
  });

  const mesh = new THREE.Mesh(geometry, material);
  mesh.position.z = PLANE_Z;

  function update(elapsed) {
    const inPaletteGlitch = paletteCycler.update(elapsed);
    const palette = paletteCycler.palette;

    uniforms.uTime.value = elapsed;
    uniforms.uColorA.value.copy(palette[0]);
    uniforms.uColorB.value.copy(palette[1]);
    uniforms.uColorC.value.copy(palette[2] ?? palette[0]);
    uniforms.uColorD.value.copy(palette[3] ?? palette[1]);
    uniforms.uGlitch.value = inPaletteGlitch ? 1 : 0;
    uniforms.uFadeIn.value = smoothstep(
      Math.min(elapsed / FADE_IN_DURATION, 1)
    );

    return inPaletteGlitch;
  }

  return {
    mesh,
    update,
    // the shader fills the whole screen (unlike the mostly-black other
    // scenes), so the shared bloom pass needs to be much less aggressive
    // here or every pixel blows out
    bloom: { strength: 0.6, radius: 1.2, threshold: 0.1 },
  };
}
